version: '3.5'

services:
  registry-service:
    container_name: eureka-container
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
    - "8767:8767"
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      EUREKA_SERVER: http://localhost:8761/eureka/
    depends_on:
      - gateway
      - registry-service
    ports:
    - "4043:4043"
    links:
      - mongodb
  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      EUREKA_SERVER: http://localhost:8761/eureka/
    depends_on:
      - gateway
      - registry-service
    ports:
    - "4044:4044"
    links:
      - mongodb
  gateway:
    container_name: gateway-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      EUREKA_SERVER: http://localhost:8761/eureka/
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/#
    depends_on:
      - registry-service
    ports:
      - "4045:4045"
  mongodb:
    image: mongo:latest
    container_name: "my-mongodb"
    ports:
      - 27017:27017