server:
  port: 4040
spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      database: USER
      host: my-mongodb
      port: 27017
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
