server:
  port: 4041
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      database: PRODUCT
      host: localhost
      port: 27017
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

  instance:
    hostname: localhost
